"""Public document retrieval interface."""

from src.rag.retrieval.bm25 import (
    BM25RetrievalConfigurationError,
    BM25RetrievalInputError,
    BM25Retriever,
)
from src.rag.retrieval.bm25_index import (
    BM25Index,
    BM25IndexSnapshot,
    BM25IndexStatus,
    DuplicateChunkIDError,
)
from src.rag.retrieval.dense import (
    DenseRetrievalConfigurationError,
    DenseRetrievalInputError,
    DenseRetriever,
    QueryEmbedder,
)
from src.rag.retrieval.fusion import (
    RRFFusionConfigurationError,
    RRFFusionConflictError,
    RRFFusionDuplicateError,
    reciprocal_rank_fusion,
)
from src.rag.retrieval.tokenizer import JiebaTokenizer, Tokenizer
from src.rag.retrieval.pipeline import (
    HybridRetrievalPipeline,
    RankedRetriever,
    RetrievalDiagnostics,
    RetrievalHitDiagnostic,
    RetrievalResult,
    RetrievalPipelineConfigurationError,
    RetrievalPipelineInputError,
)
from src.rag.retrieval.exceptions import (
    BM25RetrievalUnavailableError,
    DenseRetrievalUnavailableError,
    RetrievalContractError,
    RetrievalError,
    RetrievalPathUnavailableError,
    RetrievalUnavailableError,
    VectorStoreUnavailableError,
)
from src.rag.retrieval.reranker import (
    NoOpReranker,
    UnavailableReranker,
    RerankScore,
    Reranker,
    RerankerAdapter,
    RerankerClient,
    RerankerConfigurationError,
    RerankerError,
    RerankerInputError,
    RerankerRequestError,
    RerankerResponseError,
    RerankerStatus,
    RerankScoringClient,
    RerankTransport,
    UrllibRerankTransport,
    build_reranker,
    get_reranker_status,
)

__all__ = [
    "BM25Index",
    "BM25IndexSnapshot",
    "BM25IndexStatus",
    "BM25RetrievalConfigurationError",
    "BM25RetrievalInputError",
    "BM25Retriever",
    "BM25RetrievalUnavailableError",
    "DenseRetrievalConfigurationError",
    "DenseRetrievalInputError",
    "DenseRetriever",
    "DenseRetrievalUnavailableError",
    "DuplicateChunkIDError",
    "JiebaTokenizer",
    "HybridRetrievalPipeline",
    "QueryEmbedder",
    "NoOpReranker",
    "UnavailableReranker",
    "RankedRetriever",
    "RerankScore",
    "Reranker",
    "RerankerAdapter",
    "RerankerClient",
    "RerankerConfigurationError",
    "RerankerError",
    "RerankerInputError",
    "RerankerRequestError",
    "RerankerResponseError",
    "RerankerStatus",
    "RerankScoringClient",
    "RerankTransport",
    "RetrievalDiagnostics",
    "RetrievalContractError",
    "RetrievalError",
    "RetrievalPathUnavailableError",
    "RetrievalUnavailableError",
    "RetrievalHitDiagnostic",
    "RetrievalResult",
    "RetrievalPipelineConfigurationError",
    "RetrievalPipelineInputError",
    "RRFFusionConfigurationError",
    "RRFFusionConflictError",
    "RRFFusionDuplicateError",
    "Tokenizer",
    "UrllibRerankTransport",
    "VectorStoreUnavailableError",
    "build_reranker",
    "get_reranker_status",
    "reciprocal_rank_fusion",
]
